card/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from card import views
from teont import settings

app_name = 'card'
urlpatterns = [


]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tapme/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from tapme import views
from teont import settings
from card.views import ViewCard

app_name = 'tapme'
urlpatterns = [
    path('customer/', include('customer.urls')),
    path('card/', include('card.urls')),
    path('', views.Login.as_view(),name='index'),
    path('login/', views.Login.as_view() ,name='login'),
    path('logout/', views.Logout.as_view(),name='logout'),
    path('register/', views.Register.as_view(),name='register'),
    path('reset-password/', views.ResetPassword.as_view(),name='reset_password'),
    path('404/', views.Page_404.as_view(),name="page_404"),
    path('<int:card_id>/', ViewCard.as_view(), name = "view_card"),


]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

teont/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tapgo/', include('tapme.urls')),
]

tapme/models.py
from django.db import models

# Create your models here.

tapme/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Model
from django.http import request, HttpRequest
from django.shortcuts import render, redirect

# Create your views here.
from django.template import RequestContext
from django.views import View

from card.models import Card
from customer.models import InfoUser


class Index(View):
    def get(self,request):
        if request.user.is_authenticated:
            return redirect('tapme:customer:customer_profile')
        return render(request, "tapme/login.html",{});

class Login(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('tapme:customer:customer_profile')
        context = {}
        return render(request, "tapme/login.html", context);
    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('tapme:customer:customer_profile')
        else:
            messages.error(request, 'Sai tài khoản hoặc mật khẩu!')
            return render(request, "tapme/login.html", {});

class ChangeInfoUser(View):
    def post(self, request):
        username = request.POST['username']
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']

        user = authenticate(request, username=username, password=old_password)

        if user is not None:
            user = User.objects.get(username=username)
            user.set_password(new_password)
            user.save()
            return redirect('tapme:customer:customer_profile')
        else:
            messages.error(request, 'Sai tài khoản hoặc mật khẩu!')
            return render(request, "tapme/login.html", {});

class Register(View):
    def get(self,request):
        if request.user.is_authenticated:
            return redirect('tapme:customer:customer_profile')
        return render(request, "tapme/register.html",{});
    def post(self, request):
        username = request.POST["username"]
        email = request.POST["email"]
        card_id = request.POST["card_id"]
        password1 = request.POST["password"]
        password2 = request.POST["repeat_password"]
#         -------Kiem tra user, sdt, email, card code da ton tai chua------
        if is_username_exist(username):
            messages.info(request, 'Tài khoản đã tồn tại!')
            return render(request, "tapme/register.html", {});
        else:
            # --------Kiem tra email ton tai chua-------
            if is_email_exist(email):
                messages.info(request, 'Email đã tồn tại!')
                return render(request, "tapme/register.html", {});
            else:
                # --------Kiem tra card da lien ket voi user nao chua-------
                if is_empty_card_id(card_id) == False:
                    messages.info(request, 'Sai mã thẻ, vui lòng kiểm tra lại!')
                    return render(request, "tapme/register.html", {});
                else:
    #                -----------Dang ky tai khoan----------------
                    if password1 == password2 and password1 != '' and password2 != '':
                        user = User.objects.create_user(username=username, email=email, password=password2)
                        messages.success(request, 'Tạo tài khoản thành công')
                    #     ------Cap nhat lai card-------
                        card = Card.objects.get(id=int(card_id))
                        card.user = User.objects.get(username=username)
                        card.save()
                    # -----------Tao info user-----
                        InfoUser.objects.create(user=user, avatar=settings.MEDIA_ROOT+'/avatars/avatar5.jpeg')
                    else:
                        messages.error(request, 'Vui lòng kiểm tra lại mật khẩu!')
                    return render(request, "tapme/register.html",{});

class ResetPassword(View):
    def get(self,request):
        if request.user.is_authenticated:
            return redirect('tapme:customer:customer_profile')
        return render(request, "tapme/forgotpass.html",{});

class Logout(View):
    def get(self, request):
        logout(request)
        return redirect('tapme:index')

class Page_404(View):
    def get(self, request):
        return render(request, 'tapme/../teont/templates/teont/404.html', {})


def is_email_exist(email):
    if User.objects.filter(email=email).exists():
        return True;
    else:
        return False

def is_username_exist(username):
    if User.objects.filter(username=username).exists():
        return True;
    else:
        return False

def is_empty_card_id(id):
    card = Card.objects.get(id=id)
    if card.user == None:
        return True
    else:
        return False

tapme/templates/tapme/base.html
{% load humanize %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height initial-scale=1.0, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, height=device-height initial-scale=1.0, shrink-to-fit=no">
    <title>TapGo</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome5-overrides.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="{% static 'css/Social-Icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script type="text/javascript">

        var user = '{{ request.user }}'

        function getToken(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
            return cookieValue;
        }

        const csrftoken = getToken('csrftoken');
    </script>
</head>

<body id="page-top" style="">
    <div id="wrapper">
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content" style="background: linear-gradient(140deg, #a770ef 0%, #cf8bf3 30%, #fdb99b 100%);">

                {% block navbar %}
                {% endblock navbar %}

                {% block content %}
                {% endblock %}

            </div>
        </div>
        <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
        {#  ---  Footer-----#}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="{% static 'js/theme.js' %}"></script>
</body>
<footer class="bg-white sticky-footer" style="position: relative;left: 0;bottom: 0;width: 100%; z-index: -100">
                <div class="container my-auto" >
                    <div class="text-center my-auto copyright"><span>Copyright © Nguyễn Tri Long</span></div>
                </div>
            </footer>
</html>

tapme/templates/tapme/change_password.html
{% extends 'tapme/base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid shadow-none" style="margin-top:20px;padding: 0 0;padding-bottom: 5px;">
                    <!-- Start: form-login -->
                    <div class="row d-flex justify-content-lg-center mb-3" style="margin: 0 auto;width: 100%;">
                        <div class="col col-sm-2 col-12 col-md-3"></div>
                        <div class="col-lg-4 col-12 col-sm-8 col-md-6">
                            <div class="shadow-sm p-5" style="border-radius: 25px;background: var(--white);">
                                <div class="text-center">
                                    <h4 class="text-dark mb-4" style="color: rgb(0,0,0);">Thay đổi mật khẩu</h4>
                                </div>
                                <form action="{% url 'tapme:customer:change_password' %}" method="post" class="user" style="margin-top: 40px;">
                                    {% csrf_token %}
                                    <!-- Start: old_pass -->
                                    <div class="form-group row">
                                        <input name="old_password" class="form-control form-control-user" type="password" placeholder="Mật khẩu cũ">
                                    </div><!-- End: user -->
                                    <!-- Start: new_pass -->
                                    <div class="form-group row">
                                        <input name="new_password" class="form-control form-control-user" type="password" placeholder="Mật khẩu mới"></div><!-- End: name -->
                                    <!-- Start: name -->
                                    <div class="form-group row">
                                        <input name="re_new_password" class="form-control form-control-user" type="password" placeholder="Nhập lại mật khẩu mới"></div><!-- End: name -->

                                    <button class="btn btn-primary btn-block text-center text-white btn-user" type="submit" style="margin-top: 40px;">Đổi mật khẩu</button>
                                    {% if messages %}
                                        {% for message in messages %}
                                            {% if message.tags == 'error' %}
                                                <div class="alert alert-danger text-center" role="alert" style="margin: 20px">
                                                    {{ message }}
                                                </div>
                                            {% endif %}
                                            {% if message.tags == 'success' %}
                                                <div class="alert alert-success text-center" role="alert" style="margin: 20px">
                                                    {{ message }}
                                                </div>
                                            {% endif %}
                                            {% if message.tags == 'info' %}
                                                <div class="alert alert-info text-center" role="alert" style="margin: 20px">
                                                    {{ message }}
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                    <hr>
                                </form>
                                <div class="text-center"><a class="small" href="{% url 'tapme:login' %}">Đăng nhập lại!</a></div>
                            </div>
                        </div>
                        <div class="col col-sm-2 col-12 col-md-3"></div>
                    </div><!-- End: form-login -->
                </div>
{% endblock %}

tapme/templates/tapme/forgotpass.html
{% extends 'tapme/base.html' %}

{% block navbar %}
    <nav class="navbar navbar-light navbar-expand-md" style="margin: 20px 40px;">
                    <div class="container-fluid"><a class="navbar-brand" href="#" style="color: var(--light);font-size: 35px;">TapGo</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navcol-1">
                            <ul class="navbar-nav justify-content-around ml-auto" style="width: 30%;">
                                <li class="nav-item text-center"><a class="nav-link active" href="{% url 'tapme:index' %}" style="color: var(--light);">Trang chủ</a></li>
                                <li class="nav-item text-center"><a class="nav-link" href="{% url 'tapme:index' %}" style="color: var(--light);">Liên hệ</a></li>
                                <li class="nav-item text-center" style="background: #313437;border-radius: 30px;padding: 0 10px;"><a class="nav-link" href="{% url 'tapme:login' %}" style="color: var(--light);">Đăng nhập</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
{% endblock %}

{% block content %}
    <div class="container-fluid shadow-none" style="padding: 0 0;padding-bottom: 5px;">
                    <!-- Start: row-form-login -->
                    <div class="row d-flex justify-content-lg-center mb-3" style="margin: 0 auto;width: 100%;">
                        <div class="col col-sm-2 col-12 col-md-3"></div>
                        <div class="col-lg-4 col-12 col-sm-8 col-md-6">
                            <div class="shadow-sm p-5" style="border-radius: 25px;background: var(--white);margin: 40px 0;">
                                <div class="text-center">
                                    <h4 class="text-dark mb-4" style="color: rgb(0,0,0);">Lấy lại mật khẩu</h4>
                                </div><!-- Start: form-forget-pass -->
                                <form class="user" style="margin-top: 40px;">
                                    <!-- Start: email -->
                                    <div class="form-group row"><input class="form-control form-control-user" type="email" placeholder="Nhập địa chỉ Email đã đăng ký"></div><!-- End: email --><button class="btn btn-primary btn-block text-white btn-user" type="submit" style="margin-top: 40px;">Lấy lại mật khẩu</button>
                                    <hr>
                                </form><!-- End: form-forget-pass -->
                                <div class="text-center"><a class="small" href="{% url 'tapme:login' %}">Đăng nhập!</a></div>
                            </div>
                        </div>
                        <div class="col col-sm-2 col-12 col-md-3"></div>
                    </div><!-- End: row-form-login -->
                </div>
{% endblock %}

tapme/templates/tapme/login.html
{% extends 'tapme/base.html' %}
{% load humanize %}
{% load static %}


{% block navbar %}
    <nav class="navbar navbar-light navbar-expand-md" style="margin: 20px 40px;">
                    <div class="container-fluid"><a class="navbar-brand" href="{% url 'tapme:index' %}" style="color: var(--light);font-size: 35px;">TapGo</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navcol-1">
                            <ul class="navbar-nav justify-content-around ml-auto" style="width: 30%;">
                                <li class="nav-item text-center"><a class="nav-link active" href="{% url 'tapme:index' %}" style="color: var(--light);">Trang chủ</a></li>
                                <li class="nav-item text-center"><a class="nav-link" href="{% url 'tapme:index' %}" style="color: var(--light);">Liên hệ</a></li>
                                <li class="nav-item text-center" style="background: #313437;border-radius: 30px;padding: 0 10px;"><a class="nav-link" href="{% url 'tapme:register' %}" style="color: var(--light);">Đăng ký</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
{% endblock %}

{% block content %}
    <div class="container-fluid shadow-none" style="padding: 0 0;padding-bottom: 5px;">
                    <!-- Start: row-form-login -->
                    <div class="row d-flex justify-content-lg-center mb-3" style="margin: 0 auto;width: 100%;">
                        <div class="col-lg-4 col-sm-2 col-12 col-md-3"></div>
                        <div class="col-lg-4 col-12 col-sm-8 col-md-6">
                            <div class="shadow-sm p-5" style="border-radius: 25px;background: var(--white);margin: 40px 0;">
                                <div class="text-center">
                                    <h4 class="text-dark mb-4" style="color: rgb(0,0,0);">Đăng nhập</h4>
                                </div><!-- Start: form-login -->
                                <form method="post" action="{% url 'tapme:login' %}" class="user" style="margin-top: 40px;">
                                    {% csrf_token %}
                                    <!-- Start: user -->
                                    <div class="form-group row">
                                        <input name="username" id="loginUsername" class="form-control form-control-user" type="text" placeholder="Tên đăng nhập">
                                    </div><!-- End: user -->
                                    <!-- Start: pass -->
                                    <div class="form-group row">
                                        <input name="password" id="loginPassword" class="form-control form-control-user" type="password" placeholder="Mật khẩu" >
                                    </div><!-- End: pass -->
                                    <!-- Start: btn-login -->
                                    <button class="btn btn-primary btn-block text-white btn-user" type="submit" style="margin-top: 40px;">
                                        Đăng nhập
                                    </button><!-- End: btn-login -->
                                    {% if messages %}
                                        {% for message in messages %}
                                                <div class="alert alert-danger" role="alert" style="margin: 20px">
                                                    {{ message }}
                                                </div>
                                        {% endfor %}
                                    {% endif %}

                                    <hr>
                                </form><!-- End: form-login -->
                                <div class="text-center"><a class="small" href="{% url 'tapme:reset_password' %}">Quên mật khẩu?</a></div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-sm-2 col-12 col-md-3"></div>
                    </div><!-- End: row-form-login -->
                </div>
{% endblock %}

tapme/templates/tapme/page_system_404.html
{% load static %}
<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.7
Version: 4.7.5
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->

    <head>
        <meta charset="utf-8" />
        <title>Metronic Admin Theme #4 | 404 Page Option 3</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="Preview page of Metronic Admin Theme #4 for 404 page option 3" name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/simple-line-icons/simple-line-icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'bootstrap-switch/css/bootstrap-switch.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="{% static 'css/components.min.css' %}" rel="stylesheet" id="style_components" type="text/css" />
        <link href="{% static 'css/plugins.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN PAGE LEVEL STYLES -->
        <link href="{% static 'css/error.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="favicon.ico" /> </head>
    <!-- END HEAD -->

    <body class=" page-404-3">
        <div class="page-inner">
            <img src="{% static 'media/earth.jpg' %}" class="img-responsive" alt=""> </div>
        <div class="container error-404">
            <h1>404</h1>
            <h2>Houston, we have a problem.</h2>
            <p> Actually, the page you are looking for does not exist. </p>
            <p>
                <a href="{% url 'tapme:index' %}" class="btn red btn-outline"> Return home </a>
                <br> </p>
        </div>
        <!--[if lt IE 9]>
<script src="{% static 'js/respond.min.js' %}"></script>
<script src="{% static 'js/excanvas.min.js' %}"></script>
<script src="{% static 'js/ie8.fix.min.js' %}"></script>
<![endif]-->
        <!-- BEGIN CORE PLUGINS -->
        <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/js.cookie.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/jquery-slimscroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/jquery.blockui.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'css/bootstrap-switch/js/bootstrap-switch.min.js' %}" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="{% static 'js/app.min.js' %}" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <!-- END THEME LAYOUT SCRIPTS -->
        <script>
            $(document).ready(function()
            {
                $('#clickmewow').click(function()
                {
                    $('#radio1003').attr('checked', 'checked');
                });
            })
        </script>
    </body>

</html>

tapme/templates/tapme/register.html
{% extends 'tapme/base.html' %}

{% block navbar %}
    <nav class="navbar navbar-light navbar-expand-md" style="margin: 20px 40px;">
                    <div class="container-fluid"><a class="navbar-brand" href="#" style="color: var(--light);font-size: 35px;">TapGo</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navcol-1">
                            <ul class="navbar-nav justify-content-around ml-auto" style="width: 30%;">
                                <li class="nav-item text-center"><a class="nav-link active" href="{% url 'tapme:index' %}" style="color: var(--light);">Trang chủ</a></li>
                                <li class="nav-item text-center"><a class="nav-link" href="{% url 'tapme:index' %}" style="color: var(--light);">Liên hệ</a></li>
                                <li class="nav-item text-center" style="background: #313437;border-radius: 30px;padding: 0 10px;"><a class="nav-link" href="{% url 'tapme:login' %}" style="color: var(--light);">Đăng nhập</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
{% endblock %}

{% block content %}
    <div class="container-fluid shadow-none" style="padding: 0 0;padding-bottom: 5px;">
                    <!-- Start: form-login -->
                    <div class="row d-flex justify-content-lg-center mb-3" style="margin: 0 auto;width: 100%;">
                        <div class="col col-sm-2 col-12 col-md-3"></div>
                        <div class="col-lg-4 col-12 col-sm-8 col-md-6">
                            <div class="shadow-sm p-5" style="border-radius: 25px;background: var(--white);">
                                <div class="text-center">
                                    <h4 class="text-dark mb-4" style="color: rgb(0,0,0);">Tạo tài khoản mới</h4>
                                </div>
                                <form method="post" class="user" style="margin-top: 40px;">
                                    {% csrf_token %}
                                    <!-- Start: user -->
                                    <div class="form-group row">
                                        <input name="username" class="form-control form-control-user" type="text" placeholder="Tên đăng nhập">
                                    </div><!-- End: user -->
                                    <!-- Start: name -->
                                    <div class="form-group row">
                                        <input name="email" class="form-control form-control-user" type="email" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Email"></div><!-- End: name -->
                                    <!-- Start: name -->
                                    <div class="form-group row">
                                        <input name="card_id" class="form-control form-control-user" type="number" placeholder="Mã số thẻ của bạn"></div><!-- End: name -->
                                    <!-- Start: name -->
                                    <div class="form-group row">
                                        <input name="password" class="form-control form-control-user" type="password" placeholder="Mật khẩu"></div><!-- End: name -->
                                    <!-- Start: name -->
                                    <div class="form-group row">
                                        <input name="repeat_password" class="form-control form-control-user" type="password" placeholder="Nhập lại mật khẩu"></div><!-- End: name -->
                                    <button class="btn btn-primary btn-block text-center text-white btn-user" type="submit" style="margin-top: 40px;">Tạo tài khoản</button>
                                    {% if messages %}
                                        {% for message in messages %}
                                            {% if message.tags == 'error' %}
                                                <div class="alert alert-danger text-center" role="alert" style="margin: 20px">
                                                    {{ message }}
                                                </div>
                                            {% endif %}
                                            {% if message.tags == 'success' %}
                                                <div class="alert alert-success text-center" role="alert" style="margin: 20px">
                                                    {{ message }}
                                                </div>
                                            {% endif %}
                                            {% if message.tags == 'info' %}
                                                <div class="alert alert-info text-center" role="alert" style="margin: 20px">
                                                    {{ message }}
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                    <hr>
                                </form>
                                <div class="text-center"><a class="small" href="{% url 'tapme:login' %}">Đã có tài khoản? Đăng nhập ngay!</a></div>
                            </div>
                        </div>
                        <div class="col col-sm-2 col-12 col-md-3"></div>
                    </div><!-- End: form-login -->
                </div>
{% endblock %}