card/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from card import views
from teont import settings

app_name = 'card'
urlpatterns = [


]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

customer/urls.py
from django.conf.urls.static import static
from django.urls import path, include

import tapme
from customer import views
from teont import settings

app_name = 'customer'
urlpatterns = [
    path('profile/', views.ViewProfile.as_view(),name='customer_profile'),
    path('social/', views.ViewSocial.as_view(),name='customer_social'),
    path('change-password/', views.ChangePassword.as_view(),name='change_password'),
    path('change_info/', views.ChangeInfoUser.as_view(), name='change_info'),
    path('change_address/', views.ChangeAddress.as_view(), name='change_address'),
    path('change_avatar/', views.ChangeAvatar.as_view(), name='change_avatar'),
    path('add_social/', views.AddSocial.as_view(), name='add_social'),
    path('change_social/', views.ChangeSocial.as_view(), name='change_social'),
    path('delete_social/', views.DeleteSocial.as_view(), name='delete_social'),
    path('demo/', views.Demo.as_view(), name='demo'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tapme/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from tapme import views
from teont import settings
from card.views import ViewCard

app_name = 'tapme'
urlpatterns = [
    path('customer/', include('customer.urls')),
    path('card/', include('card.urls')),
    path('', views.Login.as_view(),name='index'),
    path('login/', views.Login.as_view() ,name='login'),
    path('logout/', views.Logout.as_view(),name='logout'),
    path('register/', views.Register.as_view(),name='register'),
    path('reset-password/', views.ResetPassword.as_view(),name='reset_password'),
    path('404/', views.Page_404.as_view(),name="page_404"),
    path('<int:card_id>/', ViewCard.as_view(), name = "view_card"),


]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

teont/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tapgo/', include('tapme.urls')),
]

customer/models.py
from django.db import models
from django.contrib.auth.models import User

from card.models import Card
from social.models import Social
# Create your models here.
class InfoUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True, null=True)
    sub_name = models.CharField(max_length=255, null=True, blank=True);
    phone = models.CharField(max_length=10, null=True, blank=True);
    province = models.CharField(max_length=255, null=True, blank=True);
    district = models.CharField(max_length=255, null=True, blank=True);
    commune = models.CharField(max_length=255, null=True, blank=True);
    avatar = models.ImageField(default='statics/media/avatars/avatar5.jpeg',null=True, blank=True)

    def __str__(self):
        return self.user.username

    @property
    def avatarURL(self):
        try:
            url = self.avatar.url
        except:
            url = ''
        return url

class UserSocial(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True, null=True)
    social = models.ForeignKey(Social, on_delete=models.CASCADE,blank=True, null=True)
    url_social = models.CharField(max_length=255,null=True, blank=True)
    url_scheme = models.CharField(max_length=255,null=True, blank=True)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

customer/forms.py
from PIL import Image

from django import forms
from django.core.files import File

from .models import InfoUser

class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = InfoUser
        fields = ('avatar', 'x', 'y', 'width', 'height', )
        widgets = {
            'avatar': forms.FileInput(attrs={
                'accept': 'image/*','class':'custom-file-input'  # this is not an actual validation! don't rely on that!
            })
        }

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

customer/views.py
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from PIL import Image

import validators
from pip._vendor import requests

import customer
from social.models import Social
from teont import settings
from .forms import PhotoForm
from .models import InfoUser,UserSocial
# Create your views here.
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

class ViewProfile(LoginRequiredMixin,View):
    login_url = 'tapme//login/'
    def get(self,request):
        user = request.user
        customer, created = InfoUser.objects.get_or_create(user=user)
        social = UserSocial.objects.filter(user=user)
        form = PhotoForm()
        context = {
            'customer':customer,
            'socials': social,
            'form':form,
        }
        return render(request, "customer/customer_profile.html", context);
    def post(self, request):
        username = request.POST['username']

class ViewSocial(LoginRequiredMixin,View):
    login_url = 'tapme//login/'
    def get(self,request):
        user = User.objects.get(username=request.user.username)
        customer, created = InfoUser.objects.get_or_create(user=user)
        social_customer = user.usersocial_set.all().order_by('social__id')

        # Lấy danh sách id những social đã liên kết của user hiện tại
        list_id_social_customer = user.usersocial_set.all().values_list('social__id', flat=True)

        # Lọc ra những social chưa liên kết với user, tránh liên kết trùng lặp 1 social 2 lần
        socials = Social.objects.exclude(id__in=list_id_social_customer)

        context = {
            'customer': customer,
            'social_customer': social_customer,
            'socials':socials
        }
        return render(request, "customer/customer_social.html", context);

class ChangePassword(LoginRequiredMixin,View):
    login_url = 'tapme/login/'
    def get(self,request):
        context = {}
        return render(request, "tapme/change_password.html", context);
    def post(self, request):
        username = request.user.username
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        re_new_password = request.POST['re_new_password']

        user = authenticate(request, username=username, password=old_password)

        # Kiem tra mat khau cu
        if user is None: #mat khau cu sai
            messages.error(request, 'Sai mật khẩu!')
            return render(request, "tapme/change_password.html", {});
        else: #mat khau cu dung
            # Kiem tra 2 mat khau moi
            if new_password != re_new_password:
                messages.error(request, 'Nhập lại mật khẩu mới sai!')
                return render(request, "tapme/change_password.html", {});
            else:
                user = User.objects.get(username=username)
                user.set_password(new_password)
                user.save()
                messages.success(request, 'Thay đổi mật khẩu thành công')
                return render(request, "tapme/change_password.html", {});

class ChangeInfoUser(LoginRequiredMixin,View):
    login_url = 'tapme/login/'
    def get(self, request):
        customer = InfoUser.objects.get(user=request.user)
        context = {'customer': customer}
        return render(request, 'tapme/register.html',context)
    def post(self, request):
        user = request.user
        full_name = request.POST['full_name']
        sub_name = request.POST['sub_name']
        phone_number = request.POST['phone_number']
        email = request.POST['email']

        customer, created = InfoUser.objects.get_or_create(user=request.user)
        # Thay doi so dien thoai
        # Kiem tra sdt co trung khong

        if phone_number != InfoUser.objects.get(user=user).phone:
            if InfoUser.objects.filter(phone=phone_number).exists():
                data = {
                    'tag':'error',
                    'title': '',
                    'data': 'Số điện thoại đã tồn tại. Vui lòng chọn số khác!'
                }
                return JsonResponse(data)
            else:
                customer.phone = phone_number

        # # Thay doi email
        # # Kiem tra email co trung khong
        #
        if email != User.objects.get(username=request.user.username).email:
            if User.objects.filter(email=email).exists():
                data = {
                    'tag': 'error',
                    'title': '',
                    'data': 'Email đã tồn tại. Vui lòng chọn email khác!'
                }
                return JsonResponse(data)
            else:
                user.email = email
        # Thay doi sub name
        customer.sub_name = sub_name

        # Thay doi full name
        user.first_name = full_name


        # Luu thay doi
        customer.save()
        user.save()
        # return thanh cong
        data = {
            'tag':'success',
            'title': '',
            'data': 'Thay đổi thông tin thành công'
        }
        return JsonResponse(data)

class ChangeAddress(LoginRequiredMixin,View):
    login_url = 'tapme/login/'
    def get(self, request):
        return render(request, 'tapme/register.html',{})
    def post(self, request):
        user = request.user
        province = request.POST['province']
        district = request.POST['district']
        commune = request.POST['commune']

        customer, created = InfoUser.objects.get_or_create(user=request.user)
        customer.province = province
        customer.district = district
        customer.commune = commune

        customer.save()
        data = {
            'tag':'success',
            'data': 'Thay đổi địa chỉ thành công'
        }
        return JsonResponse(data)

class ChangeAvatar(LoginRequiredMixin,View):
    login_url = 'tapme/login/'
    def post(self, request):
        # Thay doi anh dai dien
        if "user_avatar" in request.FILES:
            customer = InfoUser.objects.get(user=request.user)
            social = UserSocial.objects.filter(user=request.user)
            # Lấy file từ request
            myfile = request.FILES["user_avatar"]

            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)

            uploaded_file_url = fs.path(filename)


            x = float(request.POST["x"])
            y = float(request.POST["y"])
            w = float(request.POST["width"])
            h = float(request.POST["height"])

            image = Image.open(uploaded_file_url)
            cropped_image = image.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((720, 720), Image.ANTIALIAS)
            resized_image.save(uploaded_file_url)
            customer.avatar.delete();
            customer.avatar =  uploaded_file_url.split("media/")[1]
            customer.save();
            return redirect('tapme:customer:customer_profile')
        else:
            return redirect('tapme:page_404')

class AddSocial(LoginRequiredMixin,View):
    login_url = 'tapme/login/'
    def post(self, request):
        user = User.objects.get(username=request.user.username)
        url_social = request.POST["social_url"]
        social_id = int(request.POST["social_id"])
        social = Social.objects.get(id=social_id)
        url_scheme = getSchemeUrl(social_id, url_social)

        if social_id == 7:
            url_social = str(url_social)
            user_social = UserSocial.objects.create(user=request.user, social=social,url_social=url_social, url_scheme=url_scheme)
            # Lưu thành công
            if user_social:
                user_social.save()
                context = {
                    "tag": "success",
                    "data": "Thêm mạng xã hội thành công"
                }
                return JsonResponse(context)

            # Lưu thất bại
            else:
                context = {
                    "tag": "error",
                    "data": "Không tìm thấy mạng xã hội"
                }
                return JsonResponse(context)

        if social_id == 2:
            url_social = str(url_social)

            # Kiem tra do dai neu url la so dien thoai
            if len(url_social) != 10:
                context = {
                    'tag':'error',
                    'data': 'Vui lòng nhập đúng số điện thoại'
                }
                return JsonResponse(context)
            else:
                #     Tìm thấy social
                if social:

                    user_social = UserSocial.objects.create(user=request.user, social=social,url_social=url_social, url_scheme=url_scheme)

                    # Lưu thành công
                    if user_social:
                        user_social.save()
                        context = {
                            "tag": "success",
                            "data": "Thêm mạng xã hội thành công"
                        }
                        return JsonResponse(context)

                    # Lưu thất bại
                    else:
                        context = {
                            "tag": "error",
                            "data": "Không tìm thấy mạng xã hội"
                        }
                        return JsonResponse(context)

                #     không tìm thấy social hoặc url không đúng format
                else:
                    context = {
                        "tag": "error",
                        "data": "Không tìm thấy mạng xã hội"
                    }
                    return JsonResponse(context)

        else:
            if social_id == 3 or social_id == 4 or social_id == 5:
                user_social = UserSocial.objects.create(user=request.user, social=social, url_social=url_social,

customer/templates/customer/base.html
{% load humanize %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>TapGo</title>
   <link rel="stylesheet" href="{% static 'semantic/css/semantic.min.css' %}">
   <link rel="stylesheet" href="{% static 'semantic/css/icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'semantic/css/button.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome5-overrides.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="{% static 'css/Social-Icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap-toastr/toastr.min.css' %}"/>
    {% block css %}

    {% endblock %}

    <script type="text/javascript">
        var user = '{{ request.user }}'

        function getToken(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
            return cookieValue;
        }

        const csrftoken = getToken('csrftoken');
    </script>
</head>

<body id="page-top" class="sidebar-toggled">

    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0 toggled" style="background: linear-gradient(140deg, #a770ef, #cf8bf3 30%, #fdb99b), rgb(235,235,245);color: rgb(19,19,19);border-style: none;">
            <div class="container-fluid d-flex flex-column p-0"><a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">
                    <div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-laugh-wink" style="color: var(--light);"></i></div>
                    <div class="sidebar-brand-text mx-3"><span style="color: var(--light);">tapT</span></div>
                </a>
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    <li class="nav-item" style="color: #131313;"><a class="nav-link active" href="{% url 'tapme:customer:customer_profile' %}"><i class="fas fa-user" style="color: var(--light);"></i><span style="color: var(--light);padding: 0 20px;">Thông tin cá nhân</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'tapme:customer:customer_social' %}"><i class="fas fa-table" style="color: var(--light);"></i><span style="color: var(--light);padding: 0 20px;">Mạng xã hội</span></a></li>
                    <li class="nav-item"></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'tapme:logout' %}"><i class="fa fa-arrow-circle-o-right" style="color: var(--light);"></i><span style="color: var(--light);padding: 0 20px;">Đăng xuất</span></a></li>
                </ul>
                <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
            </div>
        </nav>
        {% block content %}
        {% endblock content %}
        <a class="border rounded d-inline scroll-to-top" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a><!-- Start: navbar-left -->
        <div>

        </div><!-- End: navbar-left -->
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="{% static 'js/theme.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap-toastr/toastr.min.js' %}" type="text/javascript"></script>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    {% block js %}

    {% endblock %}
</body>
    <footer class="bg-white sticky-footer"
            style="position: relative;left: 0;bottom: 0;width: 100%;">
        <div class="container my-auto" >
            <div class="text-center my-auto copyright"><span>Copyright © Nguyễn Tri Long</span></div>
        </div>
    </footer>
</html>